### PR TITLE
Serialize string and primitive collections

### LINKED ISSUE #2: Consider supporting of serializing a gauge with the value a collection
By default a Dropwizard app exposes a gauge which reports a set of names of deadlocked threads.
See https://github.com/dropwizard/metrics/blob/3.2-development/metrics-jvm/src/main/java/com/codahale/metrics/jvm/ThreadStatesGaugeSet.java#L82

Currently the reporter throws an `IllegalArgumentException` for this metric and writes a warning in the log:
```
WARN  c.k.d.m.i.t.DropwizardTransformer: InfluxDbMeasurement field 'deadlocks' must be String or primitive: []
```

It would be nice to report the value of this metric as a string (a result of `toString` on the collection).

### PR DESCRIPTION
**Pull request by kyeah**
## What

Permits string and primitive collections as serializable measurement values.

## Why

Fixes #2 — allows the InfluxDB reporter to report the names of app threads that are deadlocked.

I'm being cautious here and not allowing arbitrary collection objects, but leaving the serialization details up to the collection's `toString` method — we don't need to filter out NaN values or postfix integers as e.g. `1i` here, since we're sending these collections as strings instead of influxdb integers/floats/doubles.

## Who

Assigning assorted java humans

h/t. @arteam :wave:

### CODE REVIEW

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 1]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+      } else if (value != null) {
+        final Optional<String> fieldString = validatedPrimitiveField(key, value);
+        fieldString.ifPresent(s -> fields.put(key, s));
+      }
+
+      return this;
+    }
+
+    /**
+     * Validates that the collection only contains Strings and primitives.
```
Comment (tiegz) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: if we include all primitives, should our list above include `Short`, `Byte`  and `Character` too?  (I don't know enough background to know if that's realistic in this lib 😬 ) 

PS on that note, I wonder if there's a builtin list of java primitives? 🤔

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 2]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+     * Validates that the field is a String or primitive.
+     *
+     * @return true if the field is a String or primitive.
+     */
+    private static <T> boolean isValidField(final T value) {
+      return VALID_FIELD_CLASSES.stream().anyMatch(klass -> klass.isInstance(value));
+    }
+
+    /**
+     * Validates that the field is a String or primitive.
```
Comment (tiegz) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: if we need the above 3 primitives that I mentioned above, should they be included in this method too?

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 3]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+      return collection.toString();
+    }
+
+    /**
+     * Validates that the field is a String or primitive.
+     *
+     * @return true if the field is a String or primitive.
+     */
+    private static <T> boolean isValidField(final T value) {
+      return VALID_FIELD_CLASSES.stream().anyMatch(klass -> klass.isInstance(value));
```
Comment (swoopej) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: do we not want to do the checks here that we do below for `isNaN ` and `isInfinite`?  Not sure if those can be included in a collection...

Comment (kyeah) [reply src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: We filter out NaN and Inf when writing a single field since InfluxDB [doesn't support these numerical values](https://github.com/influxdata/influxdb/issues/4089), and will blow up if we insert them into the DB.

Since we're writing collections as strings, we can serialize whatever we want, including NaN/Inf/null; I think this is desired over invalidating the entire collection.

Even the class validations are unnecessary, but I want to avoid allowing people to serialize things like `[<SomeObject@0x12345>, <SomeObject@0x90210>]` (unless they explicitly call .toString()).

Comment (swoopej) [reply src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: cool 👌

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 4]
```diff
@@ -3,10 +3,13 @@
 import com.google.auto.value.AutoValue;
 import com.google.common.annotations.VisibleForTesting;
 import com.google.common.base.Preconditions;
+import com.google.common.collect.ImmutableList;
```
Comment (frewsxcv) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: 🍦

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 5]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+     *         if the field is an invalid primitive field.
+     *
+     * @throws IllegalArgumentException if the field is not a string or primitive.
+     */
+    private static <T> Optional<String> validatedPrimitiveField(final String key, final T value) {
       if (value instanceof Float) {
         final float f = (Float) value;
         if (!Float.isNaN(f) && !Float.isInfinite(f)) {
-          fields.put(key, String.valueOf(f));
+          return Optional.of(String.valueOf(f));
```
Comment (frewsxcv) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java:215]: good use of `Optional` here

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 6]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+     *         or Collection of Strings and primitives.
      */
     public <T> Builder putField(final String key, final T value) {
-      if (value == null) {
-        return this;
+      if (value instanceof Collection<?>) {
+        final Collection collection = (Collection) value;
+        final String collString = validatedPrimitiveCollection(key, collection);
+        fields.put(key, collString);
+      } else if (value != null) {
```
Comment (frewsxcv) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java:165]: as per the `@throws` in the doc comment above, should this throw if `value == null`?

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java (hunk 3 above)
Comment (arteam) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: `Float`, `Double`, `Integer`, `Long`, `String`, and `Boolean` are all final classes, so it shouldn't make difference between the `isInstance` and identity check. Since we use generics in the `isValidField` method and Java doesn't support primitives in collections, we don't have use cases when we compare a boxed class with a primitive class (e.g. `Double.class` and `double.class`). So, I think we could declare `VALID_FIELD_CLASSES` as an immutable set and use the `contains` method which should provide a faster lookup.

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java (hunk 6 above)
Comment (kyeah) [reply src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java:165]: Invalid influxdb types like NaN/Inf/null are silently dropped; added some clarifying documentation on this behavior on the `putField/s` methods — not sure if adding warnings is helpful or would make things too noisy, considering how common I'd imagine `null` values to be.

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java (hunk 3 above)
Comment (kyeah) [reply src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java]: Good call; made these changes in 5d4b72c.

File: src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java [hunk 7]
```diff
@@ -147,34 +152,85 @@ public Builder putTag(final String key, final String value) {
...
+
+    /**
+     * Validates that the field is a String or primitive.
+     *
+     * @return an Optional containing the stringified field, or Optional.empty()
+     *         if the field is an invalid primitive field.
+     *
+     * @throws IllegalArgumentException if the field is not a string or primitive.
+     */
+    private static <T> Optional<String> validatedPrimitiveField(final String key, final T value) {
```
Comment (luoser) [inline src/main/java/com/kickstarter/dropwizard/metrics/influxdb/InfluxDbMeasurement.java:211]: nice use of optional

**Review by luoser — APPROVED** [review]
LGTM
